name: 🚀 Deploy Django

on:
    push:
        branches: [main]

jobs:
    build-deploy:
        name: 🎉 Build and Deploy

        runs-on: ubuntu-latest

        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v2.3.4

            - name: 🔨 Set up Python 3.8.6
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8.6

            - name: 🛠 Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: ▶ Run Tests
              run: |
                  python manage.py test
              env:
                  BASE_KEY: ${{ secrets.BASE_KEY }}
                  SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
                  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
                  CLEAN_AES_KEY: ${{ secrets.CLEAN_AES_KEY }}
                  NEW_AES_KEY: ${{ secrets.NEW_AES_KEY }}
                  DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}

            - name: 🔃 Restart Server
              run: |
                  mkdir tmp
                  touch tmp/restart.txt

            - name: ☁ SFTP Deploy
              uses: easingthemes/ssh-deploy@v2.1.5
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  REMOTE_PORT: 21098
                  TARGET: ${{ secrets.REMOTE_TARGET }}
