name: 🚀 Deploy Django

on:
  push:
    branches: [ main ]

jobs:

  build-deploy:
    
    name: 🎉 Build and Deploy
    
    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8.6]

    steps:

    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.4
      
    - name: 🔨 Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: 🛠 Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: ▶ Run Tests
      run: |
        python manage.py test
      env:
        BASE_KEY: ${{ secrets.BASE_KEY }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        
    - name: ☁ FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftpserver }}
        username: ${{ secrets.ftpusername }}
        password: ${{ secrets.ftppassword }}
        exclude: .git*
          - .git*/**
          - __pycache__/**
          - *.pyc
